# Generated by Django 4.2.4 on 2023-09-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_job_list_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_list_contact',
            old_name='name',
            new_name='fname',
        ),
    ]
