# Generated by Django 4.2.4 on 2023-09-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_desc_job_list_contact_jdesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_list_contact',
            name='jdesc',
        ),
    ]
